-- copy from http://lua-users.org/wiki/SciteHtmlEntities
module("htmlentities", package.seeall)
function htmlentities(str)
   local entities = {
      [' '] = '&nbsp;' ,
      ['¡'] = '&iexcl;' ,
      ['¢'] = '&cent;' ,
      ['£'] = '&pound;' ,
      ['¤'] = '&curren;' ,
      ['¥'] = '&yen;' ,
      ['¦'] = '&brvbar;' ,
      ['§'] = '&sect;' ,
      ['¨'] = '&uml;' ,
      ['©'] = '&copy;' ,
      ['ª'] = '&ordf;' ,
      ['«'] = '&laquo;' ,
      ['¬'] = '&not;' ,
      ['­'] = '&shy;' ,
      ['®'] = '&reg;' ,
      ['¯'] = '&macr;' ,
      ['°'] = '&deg;' ,
      ['±'] = '&plusmn;' ,
      ['²'] = '&sup2;' ,
      ['³'] = '&sup3;' ,
      ['´'] = '&acute;' ,
      ['µ'] = '&micro;' ,
      ['¶'] = '&para;' ,
      ['·'] = '&middot;' ,
      ['¸'] = '&cedil;' ,
      ['¹'] = '&sup1;' ,
      ['º'] = '&ordm;' ,
      ['»'] = '&raquo;' ,
      ['¼'] = '&frac14;' ,
      ['½'] = '&frac12;' ,
      ['¾'] = '&frac34;' ,
      ['¿'] = '&iquest;' ,
      ['À'] = '&Agrave;' ,
      ['Á'] = '&Aacute;' ,
      ['Â'] = '&Acirc;' ,
      ['Ã'] = '&Atilde;' ,
      ['Ä'] = '&Auml;' ,
      ['Å'] = '&Aring;' ,
      ['Æ'] = '&AElig;' ,
      ['Ç'] = '&Ccedil;' ,
      ['È'] = '&Egrave;' ,
      ['É'] = '&Eacute;' ,
      ['Ê'] = '&Ecirc;' ,
      ['Ë'] = '&Euml;' ,
      ['Ì'] = '&Igrave;' ,
      ['Í'] = '&Iacute;' ,
      ['Î'] = '&Icirc;' ,
      ['Ï'] = '&Iuml;' ,
      ['Ð'] = '&ETH;' ,
      ['Ñ'] = '&Ntilde;' ,
      ['Ò'] = '&Ograve;' ,
      ['Ó'] = '&Oacute;' ,
      ['Ô'] = '&Ocirc;' ,
      ['Õ'] = '&Otilde;' ,
      ['Ö'] = '&Ouml;' ,
      ['×'] = '&times;' ,
      ['Ø'] = '&Oslash;' ,
      ['Ù'] = '&Ugrave;' ,
      ['Ú'] = '&Uacute;' ,
      ['Û'] = '&Ucirc;' ,
      ['Ü'] = '&Uuml;' ,
      ['Ý'] = '&Yacute;' ,
      ['Þ'] = '&THORN;' ,
      ['ß'] = '&szlig;' ,
      ['à'] = '&agrave;' ,
      ['á'] = '&aacute;' ,
      ['â'] = '&acirc;' ,
      ['ã'] = '&atilde;' ,
      ['ä'] = '&auml;' ,
      ['å'] = '&aring;' ,
      ['æ'] = '&aelig;' ,
      ['ç'] = '&ccedil;' ,
      ['è'] = '&egrave;' ,
      ['é'] = '&eacute;' ,
      ['ê'] = '&ecirc;' ,
      ['ë'] = '&euml;' ,
      ['ì'] = '&igrave;' ,
      ['í'] = '&iacute;' ,
      ['î'] = '&icirc;' ,
      ['ï'] = '&iuml;' ,
      ['ð'] = '&eth;' ,
      ['ñ'] = '&ntilde;' ,
      ['ò'] = '&ograve;' ,
      ['ó'] = '&oacute;' ,
      ['ô'] = '&ocirc;' ,
      ['õ'] = '&otilde;' ,
      ['ö'] = '&ouml;' ,
      ['÷'] = '&divide;' ,
      ['ø'] = '&oslash;' ,
      ['ù'] = '&ugrave;' ,
      ['ú'] = '&uacute;' ,
      ['û'] = '&ucirc;' ,
      ['ü'] = '&uuml;' ,
      ['ý'] = '&yacute;' ,
      ['þ'] = '&thorn;' ,
      ['ÿ'] = '&yuml;' ,
      ['"'] = '&quot;' ,
      ["'"] = '&#39;' ,
      ['<'] = '&lt;' ,
      ['>'] = '&gt;' ,
      ['&'] = '&amp;'
   }
   -- Here we search for non standar characters and replace them if
   -- we have a translation. The regexp could be changed to include an
   -- exact list with the above characters [áéíó...] and then remove
   -- the 'if' below, but it's easier to maintain like this...
   return
      string.gsub(str, ".",
		  function (v)
		     if entities[v] then return entities[v] else return v end
		  end)
end
function htmlunentities()
   local entities = {
      nbsp = ' ' ,
      iexcl = '¡' ,
      cent = '¢' ,
      pound = '£' ,
      curren = '¤' ,
      yen = '¥' ,
      brvbar = '¦' ,
      sect = '§' ,
      uml = '¨' ,
      copy = '©' ,
      ordf = 'ª' ,
      laquo = '«' ,
      ['not'] = '¬' ,
      shy = '­' ,
      reg = '®' ,
      macr = '¯' ,
      ['deg'] = '°' ,
      plusmn = '±' ,
      sup2 = '²' ,
      sup3 = '³' ,
      acute = '´' ,
      micro = 'µ' ,
      para = '¶' ,
      middot = '·' ,
      cedil = '¸' ,
      sup1 = '¹' ,
      ordm = 'º' ,
      raquo = '»' ,
      frac14 = '¼' ,
      frac12 = '½' ,
      frac34 = '¾' ,
      iquest = '¿' ,
      Agrave = 'À' ,
      Aacute = 'Á' ,
      Acirc = 'Â' ,
      Atilde = 'Ã' ,
      Auml = 'Ä' ,
      Aring = 'Å' ,
      AElig = 'Æ' ,
      Ccedil = 'Ç' ,
      Egrave = 'È' ,
      Eacute = 'É' ,
      Ecirc = 'Ê' ,
      Euml = 'Ë' ,
      Igrave = 'Ì' ,
      Iacute = 'Í' ,
      Icirc = 'Î' ,
      Iuml = 'Ï' ,
      ETH = 'Ð' ,
      Ntilde = 'Ñ' ,
      Ograve = 'Ò' ,
      Oacute = 'Ó' ,
      Ocirc = 'Ô' ,
      Otilde = 'Õ' ,
      Ouml = 'Ö' ,
      times = '×' ,
      Oslash = 'Ø' ,
      Ugrave = 'Ù' ,
      Uacute = 'Ú' ,
      Ucirc = 'Û' ,
      Uuml = 'Ü' ,
      Yacute = 'Ý' ,
      THORN = 'Þ' ,
      szlig = 'ß' ,
      agrave = 'à' ,
      aacute = 'á' ,
      acirc = 'â' ,
      atilde = 'ã' ,
      auml = 'ä' ,
      aring = 'å' ,
      aelig = 'æ' ,
      ccedil = 'ç' ,
      egrave = 'è' ,
      eacute = 'é' ,
      ecirc = 'ê' ,
      euml = 'ë' ,
      igrave = 'ì' ,
      iacute = 'í' ,
      icirc = 'î' ,
      iuml = 'ï' ,
      eth = 'ð' ,
      ntilde = 'ñ' ,
      ograve = 'ò' ,
      oacute = 'ó' ,
      ocirc = 'ô' ,
      otilde = 'õ' ,
      ouml = 'ö' ,
      divide = '÷' ,
      oslash = 'ø' ,
      ugrave = 'ù' ,
      uacute = 'ú' ,
      ucirc = 'û' ,
      uuml = 'ü' ,
      yacute = 'ý' ,
      thorn = 'þ' ,
      yuml = 'ÿ' ,
      quot = '"' ,
      lt = '<' ,
      gt = '>' ,
      amp = '' 
   }

   string.gsub(str, "&%a+;",
	       function (entity)
		  return entities[string.sub(entity, 2, -2)] or entity
	       end)
   return str
end
